/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elyte;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class MainWorkerTest {
    @Test void appHasAGreeting() {
        //MainWorker classUnderTest = new MainWorker();
        
    }
}
