MYSQL_HOST: db
MYSQL_USER: userExample
MYSQL_PORT: 3306
MYSQL_DATABASE: elyte
MYSQL_ROOT_PASSWORD: 54321
MYSQL_PASSWORD: 54321
DB_URL: jdbc:mysql://localhost:3306/elyte?user=userExample&password=54321
JDBC_DRIVER: com.mysql.cj.jdbc.Driver
RABBIT_HOST: localhost
RABBITMQ_NODE_PORT: 5672
RABBITMQ_DEFAULT_USER: rabbitUser
RABBITMQ_DEFAULT_PASS: elyteRQ
LOST_QUEUE_NAME: LOST
LOST_ROUTING_KEY: lostItems
BOOKING_QUEUE_NAME: BOOKING
BOOKING_ROUTING_KEY: booking
SEARCH_QUEUE_NAME: SEARCH
SEARCH_ROUTING_KEY: search
EXCHANGE_NAME: elyteExchange